# Generated by Django 3.0.3 on 2020-02-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_type', models.CharField(max_length=64)),
                ('to_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_contacts', to='crm.Contact')),
                ('to_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_contacts', to='crm.Contact')),
                ('types', models.ManyToManyField(blank=True, related_name='contact_relationships', to='crm.RelationshipType')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.ManyToManyField(through='crm.ContactRelationship', to='crm.Contact'),
        ),
    ]
