# Generated by Django 3.0.3 on 2020-02-16 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('activity_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Contact')),
            ],
        ),
    ]
