# Generated by Django 3.0.3 on 2020-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshiptype',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
