# Generated by Django 3.0.3 on 2020-02-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200216_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactrelationship',
            name='types',
        ),
        migrations.AddField(
            model_name='contactrelationship',
            name='types',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_relationships', to='crm.RelationshipType'),
            preserve_default=False,
        ),
    ]
