# Generated by Django 3.0.3 on 2020-02-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200217_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='activites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_activity', to='crm.Activity'),
        ),
    ]
