# Generated by Django 3.0.3 on 2020-02-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200222_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_contacts', to='crm.ContactRelationship'),
        ),
    ]
