# Generated by Django 3.0.3 on 2020-02-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200222_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Contact'),
        ),
    ]
