# Generated by Django 3.0.3 on 2020-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20200222_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='contacts',
            field=models.ManyToManyField(related_name='_contact_contacts_+', through='crm.ContactRelationship', to='crm.Contact'),
        ),
    ]
