# Generated by Django 3.0.3 on 2020-02-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20200222_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Unsure', 'Unsure')], max_length=64, null=True),
        ),
    ]
