# Generated by Django 3.0.3 on 2020-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20200224_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/avatars/'),
        ),
    ]
