# Generated by Django 3.0.3 on 2020-02-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20200227_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
