# Generated by Django 3.0.3 on 2020-02-28 17:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('crm', '0023_auto_20200228_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
